### PR TITLE
Do not use temp files

### PR DESCRIPTION
**Pull request by corrideat**
I've made a patch not to use temp files, as it was causing some issues with sometimes them not being resolved. The patch encodes the CSS directly in the path, which works because of namespaces (and the file name isn't being used, as otherwise it was random temp file names).

### CODE REVIEW

**Comment by g45t345rt** [comment]
@corrideat dope dope! can I merge?

**Comment by corrideat** [comment]
Yep, it works fine from my testing. Besides running the tests and own projects, what I didn't test are preprocessors. It should be good though (well, maybe the last commit about `@import` is the one most likely to break things)

Since I made the PR:

- Now the CSS isn't inlined in the import path and is instead passed in `pluginData`. The main reason for this is so that it's possible to read error messages
- I've made a last commit that also fixes using `@import` (before it failed because the onResolve handler tried to process it and failed).

**Comment by mikekasprzak** [comment]
Woof, I can't be sure if this was the desired effect. My logged output using the `less` preprocessor is rather unreadable:

```
  public-ludumdare.com/-/app.debug.css                                              134.6kb  100.0%
   ├ temp_stylePlugin:ni:sha-256;2AJpN6mlELXa_JqK-22KP3Et8MckJn-QJDQ3EMCmj2I          6.9kb    5.1%
   ├ temp_stylePlugin:ni:sha-256;zQRhnl1pH7P5_NG2wrbJYysFi6lX5HeQDPAj-RWLrkw          5.3kb    4.0%
   ├ temp_stylePlugin:ni:sha-256;Ne-AOvsO9YcqJlTroKsaWcCRGHzF1ks8FiRvMAyi9wA          5.1kb    3.8%
   ├ temp_stylePlugin:ni:sha-256;c8SgGZXKGOyBmEmfcqnufyqFn-5eHbFDpu2rXXiIzAk          4.9kb    3.7%
   ├ temp_stylePlugin:ni:sha-256;--zf5EUWR9DF8GWZAdtx5mcd30QXUNeqbk-aDRIQ_Xo          4.4kb    3.2%
```
etc...

That said, it does appear to work behind the scenes, it's just not practical to debug. I need to guess at what file in the sourcemap actually contains the output.

**Comment by mikekasprzak** [comment]
Yes, I was expecting the original source file name.

**Comment by YangYongAn** [comment]
> Yes, I was expecting the original source file name.

I have submitted a PR, in which you can clearly see the reference path of the CSS source file, which may be helpful to you：https://github.com/g45t345rt/esbuild-style-plugin/pull/27

**Pull request merged**
